manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/romones
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: boot_protocol
      import: app/west.yml
  self:
    path: config
